//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug_Generic_name
    {
        public Drug_Generic_name()
        {
            this.Medicine_Information = new HashSet<Medicine_Information>();
        }
    
        public int ID { get; set; }
        public string Genric_Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Medicine_Information> Medicine_Information { get; set; }
    }
}
