//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine_Information
    {
        public Medicine_Information()
        {
            this.Batches = new HashSet<Batch>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int ID { get; set; }
        public string Medicine_Name { get; set; }
        public string Category { get; set; }
        public int Generic_ID { get; set; }
        public int Manufacturer_ID { get; set; }
    
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual Drug_Generic_name Drug_Generic_name { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
