//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Purchases = new HashSet<Purchase>();
        }
    
        public int ID { get; set; }
        public string Supplier_Name { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
