//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Information
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Blood_Group { get; set; }
        public string Marital_Status { get; set; }
        public System.DateTime Join_Date { get; set; }
        public int Salary { get; set; }
        public string Username { get; set; }
    
        public virtual User_Access User_Access { get; set; }
    }
}
